import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { findPhoneNumbersInText } from 'libphonenumber-js'
import axios from 'axios'

export default function Home() {

  const [value, setValue] = useState()
  const api = "https://api.sms-activate.org/stubs/handler_api.php?api_key=452f72e2b660e96d84bcfA619846c27c&action=getRentList"

  useEffect(() => {
    axios.get(api, {
      headers: {
        "Content-Type": "text/html"
      }
    })
      .then(res => console.log(res))
      .catch(err => console.log(err))

  }, [])

  const handleChange = (e) => {
    setValue(e.target.value)
    // console.log(e.target.name,e.target.value)
    // const info = findPhoneNumbersInText(`+${e.target.value}`)
    // console.log(info);

  }

  const handleClick = () => {
    const info = parsePhoneNumber('8801743963290').country
    console.log(info);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          {/* <input onChange={handleChange} type="text" name='number' /> */}

          <button onClick={handleClick}>ok</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
