import Head from 'next/head'
import Footer from '../Components/Homepage/Footer'
import FooterBottom from '../Components/Homepage/Footer/footer-bottom'
import FooterTop from '../Components/Homepage/Footer/footer-top'
import NumberList from '../Components/Homepage/NumberList'
import NoNumberList from '../Components/Homepage/NumberList/NoNumberList'
import TopDiv from '../Components/Homepage/TopDiv'


export default function Home({ data }) {

  return (
    <>
      <Head>
        <title>Free Number</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main style={{ minWidth: '18rem' }}>
        <section id='top_div' style={{ minHeight: '35vh' }} className='bg-dark text-light text-center d-flex justify-content-center align-items-center'>
          <TopDiv />
        </section>

        <section id='numberList' >
          {
            data.status === 'error' &&
            <NoNumberList className='container' />
          }
          {
            data.status === 'success' &&
            <NumberList value={data.values} className='container' />
          }
        </section>
      </main>

      <section className='mt-4'>
        <FooterTop />
        <FooterBottom />
      </section>
    </>
  )
}

export async function getServerSideProps() {
  const result = await fetch(`${process.env.CURRENT_SITE_LINK}/api/getRentNumberList`)
  const value = await result.json()

  return {
    props: {
      data: value || null
    }
  }
}